### ISSUE TITLE
Problems loading data

### ISSUE THREAD

**Issue by wangzhengtj** [jiankang1991/SauMoCo#1]
Hi, I read your paper and I would like to try to run the code, but I am stuck in the first step of loading the data, I downloaded the files containing 1000 tiles and 100000 triples from tile2vec according to your paper, when I read the data, it shows that the file is not found, your data is not stored in the same way as tile2vec, I can't run it. Can you give me some advice on how to read this data, or give me the dataset you have organized? My email is tju_wangzheng@foxmail.com

**Comment by jiankang1991** [comment]
@wangzhengtj Thank you for your interest in my work. Based on the code, you can find the utilized dataloader class ` dataGenNPY` in `utils/NAIP_data_gen.py`. It would be much easier for capturing the data structure for the code.
